src/Appstore/Bundle/HumanResourceBundle/Form/PayrollType.php
<?php

namespace Appstore\Bundle\HumanResourceBundle\Form;


use Appstore\Bundle\DomainUserBundle\Form\EmployeeProfileType;
use Doctrine\ORM\EntityRepository;
use Setting\Bundle\LocationBundle\Repository\LocationRepository;
use Setting\Bundle\ToolBundle\Entity\GlobalOption;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Validator\Constraints\NotBlank;

class PayrollType extends AbstractType
{

    /** @var  GlobalOption */
    private $option;

    function __construct( GlobalOption $option)
    {
        $this->global = $option;
    }

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $builder

            ->add('effectedMonth','text', array('attr'=>array('class'=>'m-wrap span8 datePickerMonth','placeholder'=>'Enter Effected Month','autocomplete'=>'off'),
                'constraints' =>array(
                    new NotBlank(array('message'=>'Please input effected month')),
                )
            ))
            ->add('bonusApplicable')
            ->add('arearApplicable')
            ->add('salaryType', 'choice', array(
                'attr'=>array('class'=>'m-wrap span8'),
                'expanded'      =>false,
                'multiple'      =>false,
                 'constraints' =>array(
                     new NotBlank(array('message'=>'Please Choose Salary Type')),
                 ),
                'empty_value' => '-Choose Salary Type-',
                'choices' => array(
                    'fixed' => 'Fixed',
                    'honourable' => 'Honourable',
                    'day' => 'Day',
                    'hour' => 'Hour',
                ),
            ))
            /*->add('employeeType', 'choice', array(
                'attr'=>array('class'=>'span8 m-wrap'),
                'constraints' =>array(
                    new NotBlank(array('message'=>'Select Employee Type'))
                ),
                'empty_value' => '---Select Employee Type---',
                'choices' => array(
                    'Full Time' => 'Full Time',
                    'Half Time' => 'Half Time',
                    'Contractual' => 'Contractual',
                    'Hourly' => 'Hourly'
                ),
            ))*/
            ->add('remark','textarea', array('attr'=>array('class'=>'m-wrap span12','placeholder'=>'Enter any remark')))

        ;


    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Appstore\Bundle\HumanResourceBundle\Entity\Payroll'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'employee';
    }
}

src/Appstore/Bundle/HumanResourceBundle/Resources/views/Leave/index.html.twig
{% extends '::base.html.twig' %}
{% block body %}
    <div class="container-fluid">
        <!-- BEGIN PAGE HEADER-->
        <div class="row-fluid">
            <div class="span12">
                <h3 class="page-title">
                   Manage Medicine
                </h3>
                <ul class="breadcrumb">
                    <li>
                        <i class="icon-home"></i>
                        <a href="{{ path('homepage') }}">Home</a>
                        <span class="icon-angle-right"></span>
                    </li>
                    <li>
                        <a href="{{ path('hms_medicine') }}">Manage Medicine</a>
                        <span class="icon-angle-right"></span>
                    </li>
                    <li><a href="#">View Lists</a></li>
                    <li class="pull-right btn blue disabled mini">
                        <i class="fa fa-calendar"></i>
                        {{ "now"|date("d-F-Y") }}
                    </li>
                </ul>
            </div>
        </div>
        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTENT-->
        <div class="row-fluid">
            <div class="span12">

                <div class="portlet box green tabbable">

                    <div class="portlet-title">
                        <div class="caption"><i class="icon-reorder"></i>Manage Leave</div>
                        <div class="actions">
                            <a href="javascript:" id="show"  data-trigger="hover" data-original-title="Add medicine" class=" btn red tooltips"><i class="fa fa-angle-double-down"></i> Add Leave</a>
                        </div>
                    </div>

                    <div class="portlet-body">
                        <div class="portlet-body form">
                            {% include('flash-message.html.twig')  %}
                            <!-- BEGIN FORM-->
                            <div class="hide" id="hide">
                                {{ form_start(form) }}
                                {{ form_row(form._token) }}
                                <div class="row-fluid" >
                                    <!--/span-->
                                    <div class="span6">
                                        <div class="control-group">
                                            <label class="control-label"  for="category" >Name<span class="required">*</span></label>
                                            <div class="controls">
                                                <div class="input-icon left">
                                                    <i class="icon-medkit"></i>
                                                    {{ form_widget(form.name) }}
                                                    {{ form_errors(form.name) }}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="span2">
                                        <div class="control-group">
                                            <label class="control-label"  for="category" >Unit<span class="required">*</span></label>
                                            <div class="controls">
                                                {{ form_widget(form.unit) }}
                                                {{ form_errors(form.unit) }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="span2">
                                        <div class="control-group">
                                            <label class="control-label" for="name">Purchase Price<span class="required">*</span></label>
                                            <div class="controls">
                                                <div class="input-icon left">
                                                    <i class="icon-money"></i>
                                                    {{ form_widget(form.purchasePrice) }}
                                                    {{ form_errors(form.purchasePrice) }}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="span2">
                                        <div class="control-group">
                                            <label class="control-label" for="name">Sales Price<span class="required">*</span></label>
                                            <div class="controls">
                                                <div class="input-icon left">
                                                    <i class="icon-money"></i>
                                                    {{ form_widget(form.price) }}
                                                    {{ form_errors(form.price) }}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-actions portlet box grey">
                                    <div class="pull-right">
                                        <button type="submit" class="btn green"><i class="icon-save"></i> Save</button>
                                     </div>
                                </div>
                                {{ form_end(form) }}
                            </div>
                            <!-- END FORM-->
                        </div>
                        <div class="clearfix"><br/></div>
                        <div class="portlet-body flip-scroll">
                             <table class="table table-bordered table-striped table-condensed flip-content ">

                                <thead class="flip-content ">
                                <tr class="head-blue">
                                    <th class="numeric" >Code</th>
                                    <th class="numeric" >Name</th>
                                    <th class="numeric" >Receive Price</th>
                                    <th class="numeric" >Sales Price</th>
                                    <th class="numeric" >Opening</th>
                                    <th class="numeric" >Receive Qnt</th>
                                    <th class="numeric" >Sales Qnt</th>
                                    <th class="numeric" >Stock Qnt</th>
                                    <th class="numeric" >Min. Qnt</th>
                                    <th class="numeric" >Unit</th>
                                    <th class="numeric" >Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for entity in pagination %}
                                    {% set stockQnt = ((entity.purchaseQuantity + entity.openingQuantity) - entity.salesQuantity) %}
                                    <tr {% if entity.minQuantity > 0 and stockQnt <= entity.minQuantity %} class="min" {% endif %}>
                                        <td class="numeric" >{{ entity.particularCode }}</td>
                                        <td class="numeric" ><a href="{{ path('hms_medicine_edit',{'id': entity.id })}}">{{ entity.name }}</a></td>
                                        <td class="numeric">
                                            {% if ( app.user.granted("ROLE_DOMAIN_HOSPITAL_ADMIN") or app.user.granted("ROLE_DOMAIN"))  %}
                                            <a  class="editable" data-name="purchasePrice" href="#"  data-url="{{ path('hms_medicine_inline') }}" data-type="text" data-pk="{{ entity.id }}" data-original-title="Change purcahse price">{{ entity.purchasePrice }}</a>
                                            {% endif %}
                                        </td>
                                        <td class="numeric">
                                            {% if ( app.user.granted("ROLE_DOMAIN_HOSPITAL_ADMIN") or app.user.granted("ROLE_DOMAIN"))  %}
                                            <a  class="editable" data-name="price" href="#"  data-url="{{ path('hms_medicine_inline') }}" data-type="text" data-pk="{{ entity.id }}" data-original-title="Change sales price">{{ entity.price }}</a>
                                            {% endif %}
                                        </td>
                                        <td class="numeric">
                                            {% if ( app.user.granted("ROLE_DOMAIN_HOSPITAL_ADMIN") or app.user.granted("ROLE_DOMAIN"))  %}
                                            <a  class="editable" data-name="openingQuantity" href="#"  data-url="{{ path('hms_medicine_inline') }}" data-type="text" data-pk="{{ entity.id }}" data-original-title="Change opening quantity">{{ entity.openingQuantity }}</a>
                                            {% endif %}
                                        </td>
                                        <td class="numeric" >{{ entity.purchaseQuantity|number_format }}</td>
                                        <td class="numeric" >{{ entity.salesQuantity|number_format }}</td>
                                        <td class="numeric" >{{ stockQnt }}</td>
                                        <td class="numeric">
                                            {% if ( app.user.granted("ROLE_DOMAIN_HOSPITAL_ADMIN") or app.user.granted("ROLE_DOMAIN"))  %}
                                            <a  class="editable" data-name="minQuantity" href="#"  data-url="{{ path('hms_medicine_inline') }}" data-type="text" data-pk="{{ entity.id }}" data-original-title="Change min Quantity">{{ entity.minQuantity }}</a>
                                            {% endif %}
                                        </td>
                                        <td class="numeric">{% if  entity.unit is defined and  entity.unit is not empty %}{{ entity.unit.name|default('---') }}{% endif %}</td>
                                        <td class="numeric" >
                                            {% if( entity.status == 1) %}
                                                <a class="btn mini blue btn-action" href="{{ path('hms_medicine_status', { 'id': entity.id}) }}"><i class="icon-ok"></i></a>
                                            {% else %}
                                                <a class="btn mini red btn-action" href="{{ path('hms_medicine_status', { 'id': entity.id}) }}">x</a>
                                            {% endif %}
                                            {% if ( app.user.granted("ROLE_DOMAIN_HOSPITAL_ADMIN") or app.user.granted("ROLE_DOMAIN"))  %}
                                            <a href="{{ path('hms_medicine_edit', { 'id': entity.id }) }}" class="btn green mini" ><i class="icon-edit"></i></a>
                                            <a title="Are you sure went to delete ?" href="{{ path('hms_medicine_delete', { 'id': entity.id }) }}" class="btn red mini" ><i class="icon-trash"></i></a>
                                            {% endif %}
                                        </td>
                                    </tr>

                                {% endfor %}

                                </tbody>
                            </table>
                            <div class="pagination pull-center" >
                                {{ knp_pagination_render(pagination) }}
                            </div>

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}
{% block cssBlock %}
    {% stylesheets filter='cssrewrite'
    '@HospitalBundle/Resources/public/css/invoice.css'
    %}
    <link rel="stylesheet" href="{{ asset_url }}"/>
    {% endstylesheets %}
{% endblock  %}
{% block javascriptBlock %}
    {{ parent() }}
    {% javascripts
    '@HospitalBundle/Resources/public/js/editable.js'
    '@HospitalBundle/Resources/public/js/approveProcess.js'
    %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}
{% endblock  %}
{% block documentready %}
    {{ parent() }}
    EditableInit();
{% endblock %}

src/Appstore/Bundle/HumanResourceBundle/Resources/views/Leave/new.html.twig
{% extends '::base.html.twig' %}

{% block body %}
    <div class="container-fluid">
    <!-- BEGIN category HEADER-->
    <div class="row-fluid">
        <div class="span12">
            <h3 class="category-title">
                Manage Accessories
            </h3>
            <ul class="breadcrumb">
                <li>
                    <i class="icon-home"></i>
                    <a href="{{ path('homepage') }}">Home</a>
                    <span class="icon-angle-right"></span>
                </li>
                <li>
                    <a href="{{ path('hms_medicine') }}">Accessories</a>
                    <span class="icon-angle-right"></span>
                </li>
                <li><a href="#">Manage Accessories</a></li>
                <li class="pull-right btn blue disabled mini">
                    <i class="fa fa-calendar"></i>
                    {{ "now"|date("d-F-Y") }}
                </li>
            </ul>
        </div>
    </div>
    <!-- END category HEADER-->
    <!-- BEGIN category CONTENT-->
    <div class="row-fluid">
    <div class="span12">

    <div class="portlet box green tabbable">
        <div class="portlet-title">
            <div class="caption"><i class="icon-reorder"></i>Accessories</div>
            <div class="actions">
                <div class="btn-group">
                    <a class="btn" href="#" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                        <i class="icon-cogs"></i>&nbsp;Tools
                        <i class="icon-tasks"></i>
                    </a>
                    <ul class="dropdown-menu pull-right">

                        <li><a href="{{ path('hms_medicine_new') }}"><i class="icon-plus-sign"></i>&nbsp; Create</a></li>
                        <li><a href="{{ path('hms_medicine') }}"><i class="icon-th-list"></i>&nbsp;Lists</a></li>
                        {% if(entity.id > 0 ) %}
                        <li><a href="{{ path('hms_medicine_edit',{'id':entity.id}) }}"><i class="icon-edit"></i>&nbsp;Edit</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>


    <div class="portlet-body">
        <div class="portlet-body form">
            {% include('flash-message.html.twig')  %}
            <!-- BEGIN FORM-->
            {{ form_start(form) }}
            {{ form_row(form._token) }}
            <div class="row-fluid">
                <!--/span-->
                <div class="span9">
                    <div class="control-group">
                        <label class="control-label"  for="category" >Name<span class="required">*</span></label>
                        <div class="controls">
                            <div class="input-icon left">
                                <i class="icon-medkit"></i>
                                {{ form_widget(form.name) }}
                                {{ form_errors(form.name) }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="span3">
                    <div class="control-group">
                        <label class="control-label"  for="category" >Unit<span class="required">*</span></label>
                        <div class="controls">
                            {{ form_widget(form.unit) }}
                            {{ form_errors(form.unit) }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="row-fluid">
                <!--/span-->
                <div class="span4">
                    <div class="control-group">
                        <label class="control-label"  for="category" >Pathology</label>
                        <div class="controls">
                            {{ form_widget(form.category) }}
                            {{ form_errors(form.category) }}
                        </div>
                    </div>
                </div>
                <div class="span4">
                    <div class="control-group">
                        <label class="control-label"  for="department" >Department</label>
                        <div class="controls">
                            {{ form_widget(form.department) }}
                            {{ form_errors(form.department) }}
                        </div>
                    </div>
                </div>
                <div class="span4">
                    <div class="row-fluid">
                        <div class="span12">
                            <div class="control-group">
                                <label class="control-label" for="name">Price<span class="required">*</span></label>
                                <div class="controls">
                                    <div class="input-icon left">
                                        <i class="icon-font"></i>
                                        {{ form_widget(form.price) }}
                                        {{ form_errors(form.price) }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--/span-->
            </div>
            <div class="row-fluid">
                <!--/span-->
                <div class="span12">
                    <div class="control-group">
                        <label class="control-label"  for="content" >Content</label>
                        <div class="controls">
                            <div class="input-icon left">
                                <i class="icon-medkit"></i>
                                {{ form_widget(form.content) }}
                                {{ form_errors(form.content) }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-actions portlet box grey">
                <div class="pull-right">
                    <button type="submit" class="btn green"><i class="icon-ok"></i> Save</button>
                    <button type="submit" class="btn purple"><i class="icon-refresh"></i> Reset</button>
                    {% if(entity.id > 0 ) %}
                        <a href="{{ path('hms_medicine_delete',{'id': entity.id} ) }}"  class="btn red confirm" title="Are you sure went to delete?"><i class="icon-remove"></i> Delete</a>
                    {% endif %}
                </div>
            </div>
            {{ form_end(form) }}
            <!-- END FORM-->
        </div>
    </div>
    </div>

    </div>
    </div>
    </div>
{% endblock %}