src/Appstore/Bundle/RestaurantBundle/Entity/ItemImport.php
<?php

namespace Appstore\Bundle\RestaurantBundle\Entity;

use Appstore\Bundle\AccountingBundle\Entity\AccountVendor;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * ItemImport
 *
 * @ORM\Table(name ="resturant_itemimport")
 * @ORM\Entity(repositoryClass="Appstore\Bundle\RestaurantBundle\Repository\ItemImporterRepository")
 * @ORM\HasLifecycleCallbacks
 */

class ItemImport
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="Appstore\Bundle\RestaurantBundle\Entity\RestaurantConfig", inversedBy="itemImports" , cascade={"detach","merge"} )
     **/
    private  $restaurantConfig;


    /**
     * @Gedmo\Blameable(on="create")
     * @ORM\ManyToOne(targetEntity="Core\UserBundle\Entity\User")
     **/
    private  $createdBy;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", nullable=true)
     */
    private $name;

    /**
     * @var \DateTime
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="created", type="datetime")
     */
    private $created;


    /**
     * @var \DateTime
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(name="updated", type="datetime")
     */
    private $updated;


    /**
     * @var boolean
     *
     * @ORM\Column(name="status", type="boolean")
     */
    private $status = false;

    /**
     * @var string
     *
     * @ORM\Column(name="progress", type="string", nullable=true)
     */
    private $progress = 'created';


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $path;


    /**
     * @Assert\File(
     *     maxSize = "10240k"
     * )
     */
    protected $file;


    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }



    /**
     * Sets file.
     *
     * @param ItemImport $file
     */
    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;
    }

    /**
     * Get file.
     *
     * @return ItemImport
     */
    public function getFile()
    {
        return $this->file;
    }

    public function getAbsolutePath()
    {
        return null === $this->path
            ? null
            : $this->getUploadRootDir(). $this->path;
    }

    public function getWebPath()
    {
        return null === $this->path
            ? null
            : $this->getUploadDir().'/'.$this->path;
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {

        if ($file = $this->getAbsolutePath()) {
            unlink($file);
        }
    }


    protected function getUploadRootDir()
    {
        return __DIR__.'/../../../../../web/'.$this->getUploadDir();
    }

    protected function getUploadDir()
    {
        return 'uploads/domain/'.$this->getRestaurantConfig()->getGlobalOption()->getId().'/ecommerce/';
    }

    /**
     * @ORM\PostPersist()
     */
    public function upload()
    {
        // the file property can be empty if the field is not required
        if (null === $this->getFile()) {
            return;
        }

        // use the original file name here but you should
        // sanitize it at least to avoid any security issues

        // move takes the target directory and then the
        // target filename to move to

        $filename = date('YmdHmi') . "_" . $this->getFile()->getClientOriginalName();

        $this->getFile()->move(
            $this->getUploadRootDir(),
            $filename
        );

        // set the path property to the filename where you've saved the file

        $this->path = $filename;

        // clean up the file property as you won't need it anymore
        $this->file = null;
    }

    /**
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * @param \DateTime $created
     */
    public function setCreated($created)
    {
        $this->created = $created;
    }

    /**
     * @return \DateTime
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * @param \DateTime $updated
     */
    public function setUpdated($updated)
    {
        $this->updated = $updated;
    }


   /**
     * @return boolean
     */
    public function isStatus()
    {
        return $this->status;
    }

    /**
     * @param boolean $status
     */
    public function setStatus($status)
    {
        $this->status = $status;
    }

    /**
     * @return string
     */
    public function getProgress()
    {
        return $this->progress;
    }

    /**
     * @param string $progress
     */
    public function setProgress($progress)
    {
        $this->progress = $progress;
    }


    /**
     * @return mixed
     */
    public function getCreatedBy()
    {
        return $this->createdBy;
    }

    /**
     * @param mixed $createdBy
     */
    public function setCreatedBy($createdBy)
    {
        $this->createdBy = $createdBy;
    }


    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }


    /**
     * @return mixed
     */
    public function getRestaurantConfig()
    {
        return $this->restaurantConfig;
    }

    /**
     * @param mixed $restaurantConfig
     */
    public function setRestaurantConfig($restaurantConfig)
    {
        $this->restaurantConfig = $restaurantConfig;
    }


}

src/Appstore/Bundle/RestaurantBundle/Form/ConfigType.php
<?php

namespace Appstore\Bundle\RestaurantBundle\Form;


use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;


class ConfigType extends AbstractType
{


    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder

            ->add('vatRegNo','text', array('attr'=>array('class'=>'m-wrap span8','placeholder'=>'Enter vat registration no')))
            ->add('vatPercentage','integer',array('attr'=>array('class'=>'m-wrap numeric span5','max'=> 100)))
            ->add('address','textarea',array('attr'=>array('class'=>'m-wrap span11','rows'=>5,'placeholder'=> "Enter office/store address")))
            ->add('invoiceNote','textarea',array('attr'=>array('class'=>'m-wrap span11','rows' => 3,'placeholder'=> "Enter invoice notes")))
            ->add('printFooterText','textarea',array('attr'=>array('class'=>'m-wrap span11','rows' => 3,'placeholder'=> "Enter print footer text")))
            ->add('autoPayment')
            ->add('isCustomer')
            ->add('vatEnable')
            ->add('tablePlan')
            ->add('productImage')
            ->add('additionalTable')
            ->add('additionalServe')
            ->add('posPrint')
            ->add('deliveryPrint')
            ->add('invoicePrintLogo')
            ->add('isStockHistory')
            ->add('isInvoiceTitle')
            ->add('isPrintHeader')
            ->add('isPrintFooter')
            ->add('isPrintFooter')
            ->add('printInstruction')
            ->add('kitchenPrint')
            ->add('printToken')
            ->add('isProduction')
            ->add('vatMode', 'choice', array(
                'required'    => false,
                'attr'=>array('class'=>'m-wrap span12'),
                'empty_value' => '---VAT Mode---',
                'choices' => array(
                    'including' => 'Including',
                    'excluding' => 'Excluding',
                ),
            ))
            ->add('discountType', 'choice', array(
                'required'    => false,
                'attr'=>array('class'=>'m-wrap span12'),
                'empty_value' => '---Discount Type---',
                'choices' => array(
                    'percentage' => 'Percentage',
                    'flat' => 'Flat',
                ),
            ))
             ->add('salesMode', 'choice', array(
                'required'    => false,
                'attr'=>array('class'=>'m-wrap span12'),
                'empty_value' => '---Sales Mode---',
                'choices' => array(
                    'category' => 'Category',
                    'table' => 'Table',
                ),
            ))
            ->add('payFor', 'choice', array(
                'required'    => true,
                'attr'=>array('class'=>'m-wrap span12'),
                'choices' => array(
                    'pre-pay' => 'Pre-pay',
                    'post-pay' => 'Post-pay',
                ),
            ))
            ->add('discountPercentage','integer',array('attr'=>array('class'=>'m-wrap numeric span5')))
            ->add('invoiceHeight','text',array('attr'=>array('class'=>'m-wrap numeric span12')))
            ->add('printLeftMargin','text',array('attr'=>array('class'=>'m-wrap numeric span12')))
            ->add('printTopMargin','text',array('attr'=>array('class'=>'m-wrap numeric span12')))
            ->add('templateCss','textarea',array('attr'=>array('class'=>'m-wrap span12','rows'=>10)))

        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Appstore\Bundle\RestaurantBundle\Entity\RestaurantConfig'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'restaurant_config';
    }


}

src/Appstore/Bundle/RestaurantBundle/Controller/ItemImporterController.php
<?php

namespace Appstore\Bundle\RestaurantBundle\Controller;


use Appstore\Bundle\RestaurantBundle\Entity\ItemImport;
use Appstore\Bundle\RestaurantBundle\Form\ItemImporterType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;



/**
 * ItemImporter controller.
 *
 */
class ItemImporterController extends Controller
{

    /**
     * Lists all ItemImporter entities.
     *
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();
        $config = $this->getUser()->getGlobalOption()->getRestaurantConfig();
        $entities = $em->getRepository('RestaurantBundle:ItemImport')->findBy(array('restaurantConfig'=>$config),array('updated'=>'DESC'));
        return $this->render('RestaurantBundle:ItemImporter:index.html.twig', array(
            'entities' => $entities,
        ));
    }
    /**
     * Creates a new ItemImporter entity.
     *
     */
    public function createAction(Request $request)
    {
        $entity = new ItemImport();
        $form = $this->createCreateForm($entity);
        $form->handleRequest($request);
        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $config = $this->getUser()->getGlobalOption()->getRestaurantConfig();
            $entity->setRestaurantConfig($config);
            $entity->upload();
            $em->persist($entity);
            $em->flush();
            $this->get('session')->getFlashBag()->add(
                'success',"Data has been added successfully"
            );
            return $this->redirect($this->generateUrl('restaurant_itemimporter'));
        }
        return $this->render('RestaurantBundle:ItemImporter:new.html.twig', array(
            'entity' => $entity,
            'form'   => $form->createView(),
        ));
    }

    /**
     * Creates a form to create a ItemImporter entity.
     *
     * @param ItemImport $entity The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createCreateForm(ItemImport $entity)
    {
        $globalOption = $this->getUser()->getGlobalOption();
        $form = $this->createForm(new ItemImporterType($globalOption), $entity, array(
            'action' => $this->generateUrl('restaurant_itemimporter_create'),
            'method' => 'POST',
            'attr' => array(
                'class' => 'form-horizontal',
                'novalidate' => 'novalidate',
                'enctype' => 'multipart/form-data',
            )
        ));
        return $form;
    }

    /**
     * Displays a form to create a new ItemImporter entity.
     *
     */
    public function newAction()
    {
        $entity = new ItemImport();
        $form   = $this->createCreateForm($entity);

        return $this->render('RestaurantBundle:ItemImporter:new.html.twig', array(
            'entity' => $entity,
            'form'   => $form->createView(),
        ));
    }

    public function excelDataImportAction(ItemImport $ItemImporter)
    {

        set_time_limit(0);
        ignore_user_abort(true);
        $em = $this->getDoctrine()->getManager();
        $importer = $this->get('appstore_restaurant_item_import');
        $importer->setItemImport($ItemImporter);
        $reader = $this->get('appstore.business.item.import.event.listener');
        $file =  realpath($ItemImporter->getAbsolutePath());
        $data = $reader->getData($file);
        $importer->import($data);
        $ItemImporter->setProgress('migrated');
        $this->get('session')->getFlashBag()->add(
            'success',"Data has been migration successfully"
        );
        $em->flush();
        return $this->redirect($this->generateUrl('restaurant_itemimporter'));
    }

    /**
     * Displays a form to edit an existing ItemImporter entity.
     *
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('RestaurantBundle:ItemImport')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find ItemImporter entity.');
        }

        $editForm = $this->createEditForm($entity);
        return $this->render('RestaurantBundle:ItemImporter:new.html.twig', array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),

        ));
    }

    /**
    * Creates a form to edit a ItemImporter entity.
    *
    * @param ItemImport $entity The entity
    *
    * @return \Symfony\Component\Form\Form The form
    */
    private function createEditForm(ItemImport $entity)
    {
        $globalOption = $this->getUser()->getGlobalOption();
        $form = $this->createForm(new ItemImporterType($globalOption), $entity, array(
            'action' => $this->generateUrl('restaurant_itemimporter_update', array('id' => $entity->getId())),
            'method' => 'PUT',
        ));
        return $form;
    }
    /**
     * Edits an existing ItemImporter entity.
     *
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('RestaurantBundle:ItemImport')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find ItemImporter entity.');
        }

        $editForm = $this->createEditForm($entity);
        $editForm->handleRequest($request);

        if ($editForm->isValid()) {
            $em->flush();
            return $this->redirect($this->generateUrl('restaurant_itemimporter_edit', array('id' => $id)));
        }

        return $this->render('RestaurantBundle:ItemImporter:edit.html.twig', array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),

        ));
    }
    /**
     * Deletes a ItemImporter entity.
     *
     */
    public function deleteAction(ItemImport $ItemImporter)
    {
        $em = $this->getDoctrine()->getManager();
        if ($ItemImporter) {
            $ItemImporter->removeUpload();
            $em->remove($ItemImporter);
            $em->flush();
        }
        return $this->redirect($this->generateUrl('restaurant_itemimporter'));
    }

    public function updatedAction(ItemImport $ItemImporter)
    {



    }
    public function resetedAction(ItemImport $en)
    {

    }

}

src/Appstore/Bundle/RestaurantBundle/Resources/views/ItemImporter/index.html.twig
{% extends '::base.html.twig' %}
{% block body %}
    <div class="container-fluid">
        <!-- BEGIN PAGE HEADER-->
        <div class="row-fluid">
            <div class="span12">
                <h3 class="page-title">
                    Product Excel import Lists
                </h3>
                <ul class="breadcrumb">
                    <li>
                        <i class="icon-home"></i>
                        <a href="{{ path('homepage') }}">Home</a>
                        <span class="icon-angle-right"></span>
                    </li>
                    <li>
                        <a href="{{ path('restaurant_itemimporter') }}">Product Excel import</a>
                        <span class="icon-angle-right"></span>
                    </li>
                    <li><a href="#">Product Excel importer Lists</a></li>
                    <li class="pull-right btn blue disabled mini">
                        <i class="fa fa-calendar"></i>
                        {{ "now"|date("d-F-Y") }}
                    </li>
                </ul>
            </div>
        </div>
        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTENT-->
        <div class="row-fluid">
            <div class="span12">
                <div class="portlet box green tabbable">

                    <div class="portlet-title">
                        <div class="caption"><i class="icon-reorder"></i>Product Excel import Information</div>
                        <div class="actions">
                            <div class="btn-group">
                                <a class="btn red" href="{{ path('restaurant_itemimporter_new') }}"><i class="icon-plus-sign"></i>&nbsp; Create</a>
                            </div>
                        </div>
                    </div>

                    <div class="portlet-body">
                        <div class="portlet-body flip-scroll">
                            {% include('flash-message.html.twig')  %}
                            <table class="table table-bordered table-striped table-condensed flip-content ">

                                <thead class="flip-content ">
                                <tr class="head-grey">
                                    <th class="numeric" >Created</th>
                                    <th class="numeric" >Created By</th>
                                    <th class="numeric" >Name </th>
                                    <th class="numeric" >File</th>
                                    <th class="numeric" >Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for entity in entities %}
                                    <tr>
                                        <td class="numeric" >{{ entity.updated|date('d-m-Y') }}</td>
                                        <td class="numeric" >{{ entity.createdBy }}</td>
                                        <td class="numeric" ><a href="{{ path('restaurant_itemimporter_edit',{'id': entity.id })}}">{{ entity.name }}</a></td>
                                        <td class="numeric" ><a href="/{{ entity.webPath }}">Download File</a> </td>
                                        <td class="numeric" >
                                            {% if entity.progress == 'created' or entity.progress == 'invalid' %}
                                            <a href="{{ path('restaurant_itemimporter_edit', { 'id': entity.id }) }}" class="btn green mini" ><i class="icon-edit"></i></a>
                                                <a href="{{ path('restaurant_itemimporter_delete', { 'id': entity.id }) }}" class="btn red mini" ><i class="icon-remove"></i></a>
                                             <a href="{{ path('restaurant_itemimporter_migration', { 'id': entity.id }) }}" class="btn blue mini" ><i class="icon-upload-alt">&nbsp;Import</i></a>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

src/Appstore/Bundle/RestaurantBundle/Resources/views/ItemImporter/new.html.twig
{% extends '::base.html.twig' %}

{% block body %}
    <div class="container-fluid">
        <!-- BEGIN restaurant_itemimporter HEADER-->
        <div class="row-fluid">
            <div class="span12">
                <h3 class="restaurant_itemimporter-title">
                    Item Importer
                </h3>
                <ul class="breadcrumb">
                    <li>
                        <i class="icon-home"></i>
                        <a href="{{ path('homepage') }}">Home</a>
                        <span class="icon-angle-right"></span>
                    </li>
                    <li>
                        <a href="{{ path('restaurant_itemimporter') }}">Item Import</a>
                        <span class="icon-angle-right"></span>
                    </li>
                    <li><a href="#">Item Importer new/edit</a></li>
                    <li class="pull-right btn blue disabled mini">
                        <i class="fa fa-calendar"></i>
                        {{ "now"|date("d-F-Y") }}
                    </li>
                </ul>
            </div>
        </div>
        <!-- END restaurant_itemimporter HEADER-->
        <!-- BEGIN restaurant_itemimporter CONTENT-->
        <div class="row-fluid">
            <div class="span12">

                <div class="portlet box green tabbable">

                    <div class="portlet-title">
                        <div class="caption"><i class="icon-reorder"></i>Item Importer Information</div>
                        <div class="actions">
                            <div class="btn-group">
                                <a class="btn red" href="{{ path('restaurant_itemimporter_new') }}"><i class="icon-plus-sign"></i>&nbsp; Create</a>
                                <a class="btn" href="{{ path('restaurant_itemimporter') }}"><i class="icon-th-list"></i>&nbsp;Lists</a>
                            </div>
                        </div>

                    </div>

                    <div class="portlet-body">

                        <div class="portlet-body form">
                            {% include('flash-message.html.twig')  %}
                            <!-- BEGIN FORM-->
                            {{ form_start(form) }}
                            {{ form_row(form._token) }}

                            <div class="row-fluid">

                                <div class="span6">
                                    <div class="control-group">
                                        <label class="control-label" for="firstName">Name</label>
                                        <div class="controls">
                                            <div class="input-icon left">
                                                <i class="icon-font"></i>
                                                {{ form_widget(form.name) }}
                                                {{ form_errors(form.name) }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row-fluid">
                                <div class="span6">
                                    <div class="control-group">
                                        <label class="control-label" for="firstName">Attach file</label>
                                        <div class="controls">
                                            <div class="fileupload fileupload-new" data-provides="fileupload">
                                                <div class="input-append">
                                                    <div class="uneditable-input span4">
                                                        <i class="icon-file fileupload-exists"></i>
                                                        <span class="fileupload-preview"></span>
                                                    </div>
                                                    <span class="btn btn-file">
													<span class="fileupload-new">Select file</span>
													<span class="fileupload-exists">Change</span>
                                                        {{ form_widget(form.file) }}
                                                        {{ form_errors(form.file) }}
													</span>
                                                    <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="clearfix"><br/></div>
                            <!--/span-->
                            <div class="form-actions portlet box grey">
                                <div class="pull-center">
                                    <button type="submit" class="btn green"><i class="icon-ok"></i> Save</button>
                                    <button type="submit" class="btn purple"><i class="icon-refresh"></i> Reset</button>
                                    {% if(entity.id > 0 ) %}
                                        <a href="{{ path('restaurant_itemimporter_delete',{'id': entity.id} ) }}"  class="btn red confirm" title="Are you sure went to delete?"><i class="icon-remove"></i> Delete</a>
                                    {% endif %}
                                </div>
                            </div>
                            {{ form_end(form) }}
                            <!-- END FORM-->
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}